### ISSUE TITLE
link of pretrained model and data is forbidden to access

### ISSUE THREAD

**Issue by jiaxinxie97** [tflsguoyu/materialgan#1]
Hi,
I tried to get the pretrained model and input data from the link, but the access is forbidden. 
<img width="802" alt="image" src="https://user-images.githubusercontent.com/46376580/179515343-20b54c26-d87c-4609-9f19-5c28493bc972.png">

**Comment by tflsguoyu** [comment]
Hi, 
Sorry I just updated the link.

**Comment by tflsguoyu** [comment]
Please check our new repo. https://github.com/tflsguoyu/svbrdf-diff-renderer
