### ISSUE TITLE
Inversion failed

### ISSUE THREAD

**Issue by Youkang-Kong** [tflsguoyu/materialgan#2]
I executed directly `script_optim_ours.py` to optimize `real_book1`, and used the origin config of this file, but it failed.
Ground truth:
![rendered](https://user-images.githubusercontent.com/19804552/192290519-2e87e840-9fce-4874-902c-376e1d0748f8.png)

Result:
![rendered](https://user-images.githubusercontent.com/19804552/192290957-c21f554d-302e-430a-ba55-a74464ad55be.png)
![tex](https://user-images.githubusercontent.com/19804552/192290994-aff8b5dd-13cd-4913-87b9-b9a4a72ac84d.png)

Loss:
![loss](https://user-images.githubusercontent.com/19804552/192290796-32b48174-92ba-4027-a6aa-f3a37244263c.png)
![loss_log](https://user-images.githubusercontent.com/19804552/192290851-c7e3aa1c-ee34-4d1c-b050-9b7def01f9d1.png)

args.txt:
```
{
  "in_dir": "data/in/",
  "mat_fn": "real_book1",
  "out_dir": "data/out/",
  "vgg_weight_dir": "data/pretrained/vgg_conv.pt",
  "gpu": 0,
  "im_res": 256,
  "epochs": 2000,
  "lr": 0.02,
  "optim_latent": true,
  "tex_init": "random",
  "num_render": 9,
  "num_render_used": 7,
  "gan_latent_type": "w+",
  "gan_latent_init": "data/pretrained/latent_avg_W+_256.pt",
  "gan_noise_init": "random",
  "sub_epochs": [
    10,
    10
  ],
  "loss_weight": [
    1000.0,
    0.001,
    -1.0,
    -1.0
  ],
  "seed": 433730952,
  "embed_tex": false,
  "jittering": false,
  "vgg_layer_weight_w": [
    0.071,
    0.071,
    0.286,
    0.572
  ],
  "vgg_layer_weight_n": [
    0.421,
    0.421,
    0.105,
    0.053
  ],
  "vgg_layer_weight_wn": [
    0.125,
    0.125,
    0.125,
    0.125
  ],
  "optim_strategy": "L|N"
}
```

**Comment by jingyangcarl** [comment]
Hi, I also get similar results with the default setting. Did you have any updates on this?

**Comment by jingyangcarl** [comment]
> 

load stylegan2 weights to solve this problem

**Comment by tflsguoyu** [comment]
Please check our new repo. https://github.com/tflsguoyu/svbrdf-diff-renderer
